init = ['git', 'init']
back = ['prev', '--edit']
forward = ['next', '--edit']
install = ['util', 'exec', '--', 'jjj', 'install']
update = ['util', 'exec', '--', 'jjj', 'update']
stash = ['util', 'exec', '--', 'jjj', 'stash']
gc = ['util', 'exec', '--', 'jjj', 'gc']
swap = ['util', 'exec', '--', 'jjj', 'swap']
push = ['util', 'exec', '--', 'jjj', 'push']
pull = ['util', 'exec', '--', 'jjj', 'pull']
branch = ['util', 'exec', '--', 'jjj', 'branch']
switch = ['util', 'exec', '--', 'jjj', 'switch']
extra-help = ['util', 'exec', '--', 'jjj', '--help']